### ISSUE TITLE
No render on home pages

### ISSUE THREAD

**Issue by PFManley** [imthenachoman/nSPTiles#13]
I've noticed that when I promote pages to home page status, the page must be reloaded to render the tiles.  I was able to reproduce this quirk on 5 home pages. My guess is the redirect function in SP hangs up the load. Instances on subpages worked fine.  I was able to remedy this problem by using an absolute URL in lieu of a relative one.  Just FYI...

**Comment by imthenachoman** [comment]
@PFManley So I will be honest. I am not sure what "promote pages to home page status" means? Doesn't that just take a page and make it a home page? If so, isn't that a one time thing and once its set it wouldn't/shouldn't be a problem any more? Just trying to understand more so I know where to look to fix the bug.

**Comment by PFManley** [comment]
Hey,

 

Sorry for any confusion…new to the hub.  You are totally right and I don’t think it’s a bug.  I just thought it might be worth a mention if anyone else was having the same issue.  I absolutely LOVE, LOVE, LOVE! nSPTiles and appreciate it greatly. Awesome work and thanks for sharing!

 

Pam

**Comment by imthenachoman** [comment]
No issues. And Thank you! Happy to hear you like it!
