### ISSUE TITLE
CEWP Files 

### ISSUE THREAD

**Issue by jbriean** [imthenachoman/nSPTiles#25]
[spjs-tilesProjA.txt](https://github.com/imthenachoman/nSPTiles/files/2447575/spjs-tilesProjA.txt)
[nSPTILES-Admin2.txt](https://github.com/imthenachoman/nSPTiles/files/2447580/nSPTILES-Admin2.txt)
[spjs-tilesHow2.txt](https://github.com/imthenachoman/nSPTiles/files/2447591/spjs-tilesHow2.txt)
@imthenachoman

**Comment by imthenachoman** [comment]
So it looks like the HTML in two of the CEWPs is all mucked up. Namely, two of them use the same `div` `id`. If I were you, this is what I would do. 

I would add a CEWP to the very top of the page (it should be loaded first) that points to one HTML file with this in it:

```
<script src="/intranet/SiteAssets/Scripts/nSPTiles.js" type="text/javascript"></script>
<link rel="stylesheet" href="/path/to/font-awesome.min.css">
```

Then I would create 3 more HTML files and put them in CEWPs wherever you want them on the page (below/after the one from above). You can change `one`/`two`/`three` to whatever you want. I'm just using them as an example.

**one:**
```
<div id="one"></div>
```

**two:**
```
<div id="two"></div>
```

**three:**
```
<div id="three"></div>
```

Lastly, I would add a CEWP at the end of the page pointing to this HTML. It should be the last thing that loads/runs:

```
<script type="text/javascript">
   nSPTiles.init("one", "group one");
   nSPTiles.init("two", "group two");
   nSPTiles.init("three", "group three");
</script>

```

**Comment by jbriean** [comment]
Thank you!!!! I really appreciate you taking the time to take a look at those. I will try it out as soon as I can and see if that fixes the issue (makes sense and looks like it will)

**Comment by jbriean** [comment]
Worked perfectly! Thank you again!!

**Comment by imthenachoman** [comment]
NP.
