### ISSUE TITLE
Launch Tile purely in Javascript

### ISSUE THREAD

**Issue by voltar** [imthenachoman/nSPTiles#4]
Hi Nachoman,

great tool! indeed terrific!!!

Is there a possibility that the Tile launches pure JavaScript? My initail situation is that I would like to launch a specific modal dialogue, rather than the dialog given with the dialog link type (showModalDialog method ) with given size of the dialogue. If I use the onclick function in the configOptions, the dialog still starts, even with my custom modal dialog hides the dialog URL, but then two modal dialogs are open ...

**Comment by Sporadius** [comment]
Hi, I have forked this excellent script to do something like that. Check: https://github.com/Sporadius/nSPTiles

**Comment by imthenachoman** [comment]
@Sporadius Wow. Thank you! I will add your code to the next release. Thank you so much!

@voltar Does @Sporadius's additions do what you need/want?

**Comment by voltar** [comment]
hi, this is great, thanks a lot!

Cheers - Gianni


Gianni Zanetti
Gyreggstr. 1
CH-6315 Oberägeri/Switzerland
PHONE / PRIVATE +41 56 634 56 20 BUSINESS + 41 44 586 27 21  MOBILE  +41 79
720 12 99

**Comment by imthenachoman** [comment]
These features (and more) have been added to version 1.5.
