### ISSUE TITLE
_vti_bin/Lists.asmx?op=GetListItems 401 (Unauthorized)

### ISSUE THREAD

**Issue by essineden** [imthenachoman/nSPTiles#6]
I am unable to use the CEWP after using the code. Is there some sort of configuration on the admin/server side before I can use it? I was able to use SPJS Tiles with the same procedure and site. 

Thank you in advance

--- 

I noticed that the siteURL is getting the wrong URL for it since it's a subsite. I changed the tilesTracker[holderID].siteURL to the correct one and it worked. I just hope it doesn't affect other rendering codes.

**Comment by imthenachoman** [comment]
@essineden Where did you see that the siteURL is getting the wrong URL? And can you tell me more about your setup so I can try to recreate the bug?

**Comment by essineden** [comment]
@imthenachoman hi, the variable I changed was _tilesTracker[holderID].siteURL_. the subsite is under the structure http://webapp:XXXX/sites/subsite. the port number is not being recognized and the error 401 is showing because it's pointing to http://webapp/sites/subsites only which is a different web application. I hope that helps.

**Comment by imthenachoman** [comment]
@essineden Yes, that helps a lot. Thank you! My code does not take into account the port #. I will fix that in the next release. Thank you!

**Comment by essineden** [comment]
Awesome! looking forward to that update :+1:

**Comment by imthenachoman** [comment]
fixed in 1.51
